# Comparación de columnas: archivo original vs base procesada (para documentar la limpieza)
raw <- readRDS("data/processed/00_titulados_raw.rds")
pro <- readRDS("data/processed/01_titulados_pregrado.rds")
cat("ORIGINAL:", nrow(raw), "filas x", ncol(raw), "columnas\n")
cat("PROCESADA:", nrow(pro), "filas x", ncol(pro), "columnas\n")
cat("ELIMINADAS:", paste(setdiff(names(raw), names(pro)), collapse = ", "), "\n")
cat("AGREGADAS:", paste(setdiff(names(pro), names(raw)), collapse = ", "), "\n")
d <- readRDS("dashboard/datos_dashboard.rds")
cat("DASHBOARD celdas:", nrow(d$celdas), "x", ncol(d$celdas), "\n")
